#!/bin/sh

set -e

declare -a currencies=(
  "USD"
  "CAD"
  "GBP"
  "EUR"
)

echo "# This file is autogenerated"
echo ""

for currency_from in "${currencies[@]}"
do
  for currency_to in "${currencies[@]}"
  do
    if [ "$currency_from" != "$currency_to" ]
    then
      rate=$(units -1 "$currency_from" "$currency_to" | tr -d "\t")

      currency_from_lower=$(echo "$currency_from" | tr '[:upper:]' '[:lower:]')
      currency_to_lower=$(echo "$currency_to" | tr '[:upper:]' '[:lower:]')

      echo "define ${currency_from_lower}2${currency_to_lower} (n) {"
      echo "  return n $rate;"
      echo "}"
      echo ""
    fi
  done
done
